language: node_js
node_js:
- 12.4.0
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- npm run dist
- firebase deploy --token "$FIREBASE_TOKEN"
env:
  global:
    secure: Sgj6mfNUWAD8ePCm3VUyVDVobjtb1jUgo/+n2rrGlVgo3dlyu0efVZMsNVO7Yp//oDQD+aH7X4mWp3jpJi6d/EzuuncFWj3pz10KxqQmPUvCw4I3bCSb6CNHgtEYdu/rcxzZETVcW3JuEReIHA0KXbEVxU1dR1aN++EWMUVi3FcIDdU7+bviF0Zhgpw+Am9Sg2QglTcgwWo/tQqzEFbohjJFZRUY7SKg8wBx3d+eoxiRTtOxPgBcmOXri4v/MK66lzRK7R68feO+2pM8Ae5JJf7jOQv0WEFLhGWmboh4wcU0NHvBJj0vf1bNNjc0sLJrLd02gOeIqJlebmBH1eCJmp3i7q5grjAdWVShU4rdyKpMvRILegNB7N7Dq4zWJDGPV7bcHTbcomkx1qyNwIv1/na9AWmV6EOJLqAuMi86uV0Eh59YvwZiJO2K42IiKMHXx/m6Vqt2K/MenhElGWxV7M6fFl9yGW4V2pI443VJDiVPC5ZB+/PL/S2ous5K0757BxQRs6H9q3tNT0Rg6KvYBJZ+QOUwToORjl5Lqn6H1oBREfADiNj1A4sfyYQIe4QdRQFFs1KKIWPomhVxQySM0FV1WxrOs4AdbVrtAViRf3lcWgEPrKWv7e3xZyMQEiKB6+51GM17YlD+AvH/CamMz304MqVbaVgC4AJ0pMRA9mk=
