language: node_js
node_js:
- 9.11.1
branches:
  only:
  - master
script:
- npm run build --prod --aot
deploy:
  provider: firebase
  token:
    secure: WUOsztSbphgB0Si45EBnSDnZFnGLXSU7MtH4PoNK9OjdC1F3vDDk61J1NVhAk/J6bSGXxPzl1vhq9Qgb5b5EEE/AvCNkt2el4GEHJL721yxWS5DdkVFLEmAJMEPGr62aSunJEORcfkaDsTZIiBCrSvMYNGcBkIv2FKBYWZUZvUuuojxGDwkjO/w4rEUNj4XRKmUx5mxhmEGFO+b5bPqVe0LtQibHwtUDXutasctFUWUPHE76EMRLkMsJw5wXPcXmXtVqkAwoDnyywozsE1yOBSj/bxiPdgrf5dkdBsvDy8sC4Y2nrdhcttveGV0bVq7BeAOtoD86g5ZJtk9RR7kerM4U/tGxf8MmxLvOhnObNnmRBGesLzqgWrWHAAeTxA1vK2Gy/EJ2cY/osVGa9rz1HTwpnyQ5Ly0gOqZh9saVUPw8KnegX/U7rLobcM5DU9+s0E62kx6ooDIQQfaQm+d9laIUnoSMMHF3TFiL1jSUBPE/f2m/Fnklk0eL4AKmuTvrk+glptBYK+JtM9FboAWANhGk0dKeQe2wRHd/tbDCOO44mkOAtwLewdf7hP6dFKReZjDLtZyqsZP9SkQXELY+KAhErbc3CM1bnTB/ARC/DkkPrvdMWYhuzcS8FWeK2n2Z6Vr2FVY9f6orZx8NWmHKcXzrqTm1GPQsWJ8HjU/ldTs=
