language: node_js
node_js:
- 9.11.1
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- npm run build --prod --aot
deploy:
  provider: firebase
  token:
    secure: jcsiYY5ixflV13kTkUG73FutlWyzwq0VN0pHYMOwTLbc1sn7rfo8MqskVxKPR9D9Uc8VhW2JHGdaLznkwGuURRd0F5cFuVZrD9ByjoUdqJ/IAibtOUw0lXFuD5RrPf2p0cyt4uJ4w/MLYnBm7QRzjasvyn6wDHflSChw+orfZash/snIxSfiUx3IrSciUwszdUL49TDO/KV3fguTQ0ecTj+nmQOLHQWZs+vHMl8h8CsJHme02apaZayG4FC01NRLILrxItOCpDbbVjJfzQPIYfpFEod74q8Yo8g49eDH8zrwXyBvHwtf7ZTRzPrIlyNoICWYlm0lbaJSkDJJGvKW2oRerJ03gJ9/MtPOw66eG1q6ztelBEseZie4AqUyhhDo8VBMST5CmXUEmBQzNAbyBU2rTpxY9a1qFPJJBPlaUV5AAWxSDwILJnb2WaiNgGkByD65Z8o1c62UIJaKvZos1KgzyA5B3NbD3UBuxZrzBlKZg4C3vVvShjkQ3CvU/NXwooddIcb+NO+AiA6+ZR0G9wBa2VMV+WNb4coxbG7aZbgYRry4yJ7xjhpPAmxEnNeGc3wmbnSKe+dKRDLtt3m8yXJsrMNvN7iTv5etTo61cteEvHXGwg7r3ew5t2GXbSdUrhcGWgxTI4qiwwINCOOxsYUDZHgJpnNoe+X4JJZLse4=

