name: Publish Firebase App

on:
  push:
    branches:
      - master

jobs:
  publish:
    name : Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Install dependencies
        run: npm i
      - name: Build Application
        run: npm run build
      - name: Deploy Firebase Host
        uses: pizzafox/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: sfeir-comment
        with:
          args: deploy
